<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * my-2 my-4 my-6 my-8 my-10 my-12 my-14 my-16 my-18 my-20 my-22 my-24
 * md:my-2 md:my-4 md:my-6 md:my-8 md:my-10 md:my-12 md:my-14 md:my-16 md:my-18 md:my-20 md:my-22 md:my-24
 * lg:my-2 lg:my-4 lg:my-6 lg:my-8 lg:my-10 lg:my-12 lg:my-14 lg:my-16 lg:my-18 lg:my-20 lg:my-22 lg:my-24
 * xl:my-2 xl:my-4 xl:my-6 xl:my-8 xl:my-10 xl:my-12 lx:my-14 xl:my-16 xl:my-18 xl:my-20 xl:my-22 xl:my-24
 * 2xl:my-2 2xl:my-4 2xl:my-6 2xl:my-8 2xl:my-10 2xl:my-12 2lx:my-14 2xl:my-16 2xl:my-18 2xl:my-20 2xl:my-22 2xl:my-24
 * !mb-0
 * top-[-40px]
 */


$block_name = 'team';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes
);

$classes = implode( ' ', $all_classes );

?>

<?php if($is_preview): ?>
	<InnerBlocks class="space-y-3 min-h-50" />
<?php else: ?>

	<!-- Header -->
            <div class="">
				<InnerBlocks class="space-y-3" />
            </div>

            <!-- Calculator -->
            <div class="" x-data="{
                squareFeet: '',
                pricePerUnit: 420,
				priceLabel: 'Shingle Roof',
                get totalCost() {
                    if (!this.squareFeet || this.squareFeet <= 0) return 0;
                    return ((this.squareFeet * 1.5) / 100)* this.pricePerUnit;
                },
                get formattedCost() {
                    return new Intl.NumberFormat('en-US', {
                        style: 'currency',
                        currency: 'USD',
                        minimumFractionDigits: 2
                    }).format(this.totalCost);
                }
            }">
                <div class="space-y-6 pt-6">
                    <!-- Square Feet Input -->
                    <div>
                        <label for="squareFeet" class="block mb-2 font-semibold text-gray-700 text-sm">
                            Square Feet
                        </label>
                        <input
                            type="number"
                            id="squareFeet"
                            x-model.number="squareFeet"
                            placeholder="Enter square feet"
                            min="0"
                            step="1"
                            class="px-4 py-3 border-2 border-gray-300 focus:border-blue-500 rounded outline-none focus:ring-2 focus:ring-blue-200 w-full text-lg transition-all">
                    </div>

                    <!-- Price Per Unit Dropdown -->
                    <div>
                        <label for="pricePerUnit" class="block mb-2 font-semibold text-gray-700 text-sm">
                            Price Per Square Foot
                        </label>
                        <select
                            id="pricePerUnit"
                            x-model.number="pricePerUnit"
							@change="priceLabel = $event.target.options[$event.target.selectedIndex].getAttribute('data-label')"
                            class="px-4 py-3 border-2 border-gray-300 focus:border-blue-500 rounded outline-none focus:ring-2 focus:ring-blue-200 w-full text-lg transition-all cursor-pointer">
                            <option value="420" data-label="Shingle Roof">Shingle Roof</option>
                            <option value="550" data-label="Metal Roof">Metal Roof</option>
                            <option value="744" data-label="Tile Roof">Tile Roof</option>
                        </select>
                    </div>

                    <!-- Calculation Display -->
                    <div x-show="squareFeet > 0" x-transition class="bg-gradient-to-r from-green-50 to-emerald-50 mt-8 p-6 border-2 border-green-200 rounded">


                        <div class="">
                            <div class="flex justify-between items-center">
                                <span class="font-bold text-gray-800 text-xl">Total Estimated <span x-text="priceLabel"></span> Cost:</span>
                                <span class="font-bold text-green-600 text-3xl" x-text="formattedCost"></span>
                            </div>
                        </div>
                    </div>

                    <!-- Info Box -->
                    <div class="bg-primary/10 p-4 border-primary border-l-4 rounded">
                        <div class="flex items-start">
                            <svg class="flex-shrink-0 mt-0.5 mr-3 w-5 h-5 text-primary" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                            </svg>
                            <div class="text-sm">
                                <p>This is an approximate calculation, exact price will vary depending on specific materials used, exact square footage, roof slope, amount of wood needed to replace damaged sheathing and complexity of the job. Estimate includes average cost of the above and the price of tear off and disposal.</p>
								<p>* For a more accurate estimate, please include the total coverage area of your roof (home, garage, porch, and any other area covered area).</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

<?php endif; ?>
