<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes
 */


$block_name = 'callout';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Card default classes
$callout_default_classes = 'bg-striped p-4 md:p-6 rounded-[3rem] shadow-xl';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
	$callout_default_classes
);

$classes = implode( ' ', $all_classes );

?>

<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $classes ?>">
	<div class="px-6 lg:px-15 2xl:px-30 xl:px-20 py-6 lg:py-10 border-2 border-white rounded-4xl">
		<div class="flex lg:flex-row flex-col items-center lg:gap-6">
			<?php if (get_field('img')): ?>
				<div class="w-full lg:basis-1/4">
					<img src="<?php echo get_field('img')['url'] ?>" class="hidden lg:block drop-shadow-xl/50 w-full max-w-[275px]" alt="" />
				</div>
			<?php endif; ?>

			<div class="w-full lg:basis-3/4">
				<InnerBlocks class="space-y-3 lg:ps-10 2xl:ps-30 xl:ps-15"/>
			</div>
		</div>
	</div>
</div>

