<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes
 */


$block_name = 'cta';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Card default classes
$cta_default_classes = 'relative bg-foreground';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
	$cta_default_classes,
);

$classes = implode( ' ', $all_classes );

?>

<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $classes ?>">
	<div class="mx-auto px-6 py-6 lg:py-2 lg:text-left text-center container">
		<div class="flex lg:flex-row flex-col items-center lg:gap-2">
			<div class="w-full lg:basis-7/12">
				<InnerBlocks class="space-y-3 lg:px-14 xl:ps-0" />
			</div>
			<div class="w-full lg:basis-5/12">
				<div class="flex lg:flex-row flex-col items-center lg:gap-2">
					<div class="w-full lg:basis-1/2">
						<?php if( get_field('phone','option') ): ?>
							<a class="font-display text-primary h3" href="tel:<?php echo get_field('phone','option') ?>"><?php echo get_field('phone','option') ?></a>
						<?php endif; ?>
					</div>
					<div class="w-full lg:basis-1/2">
						<?php get_template_part( 'template-parts/components/vehicle'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

