<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 * icon-[line-md--speed-twotone-loop] icon-[line-md--speedometer-loop] size-40
 *
 */


$block_name = 'breadcrumb';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];


// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

?>

<?php if ( is_singular( 'projects' ) ) : ?>
	<nav aria-label="breadcrumbs" class="rank-math-breadcrumb"><p><a href="<?php echo esc_url(get_home_url()) ?>">Home</a><span class="separator"> &raquo; </span><a href="<?php echo get_permalink( 31 ) ?>">Projects</a><span class="separator"> &raquo; </span> <span class="last"><?php echo get_field('title', get_the_ID()); ?></span></p></nav>
<?php else:
	if (function_exists('rank_math_the_breadcrumbs')) echo '<div class="mt-3 2xl:mt-4 pb-4 xl:pb-0">'; rank_math_the_breadcrumbs(); echo '</div>';
endif; ?>

