<?php
/**
 * Tabs Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes
 */

$block_name = 'tabs';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id.
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json.
$additional_classes = $block['className'] ?? '';

// Card default classes.
$tab_default_classes = '';

// Create array $all_classes and implode.
$all_classes = array(
	$block_name,
	$additional_classes,
	$tab_default_classes,
);

$classes = implode( ' ', $all_classes );

?>

<?php if ( $is_preview ) : ?>
	<div class="bg-black h-100"></div>
<?php else : ?>
	<?php if ( have_rows( 'tabs' ) ) : ?>
		<div <?php echo esc_attr( $anchor ); ?> x-data="{
			activeTab: 0,
			images: [
			<?php
			$index = 0;
			while ( have_rows( 'tabs' ) ) :
				the_row();
				$image = get_sub_field( 'img' );
				echo $index > 0 ? ',' : '';
				echo "'" . esc_url( $image['url'] ) . "'";
				++$index;
			endwhile;
			?>
			]
		}">
			<div class="lg:gap-10 2xl:gap-16 grid grid-cols-12">
				<div class="col-span-12 lg:col-span-5">
					<div class="relative bg-white mb-8 is-style-rounded-white overflow-hidden">
						<img
							:src="images[activeTab]"
							alt="Product image"
							class="w-full h-full object-cover transition-opacity duration-300"
							x-transition>
					</div>

				</div>
				<div class="col-span-12 lg:col-span-7">
					<div>
						<div class="flex mb-6 border-gray-200 border-b overflow-x-auto">
							<?php
							$tab_index = 0;
							while ( have_rows( 'tabs' ) ) :
								the_row();
								$tab_title = get_sub_field( 'title' );
								?>
								<button
									@click="activeTab = <?php echo $tab_index; ?>"
									:class="activeTab === <?php echo $tab_index; ?> ? 'border-b-2 border-primary text-primary' : 'text-gray-600 hover:text-foreground'"
									class="px-6 py-4 font-medium whitespace-nowrap transition-colors duration-200">
									<?php echo esc_html( $tab_title ); ?>
								</button>
								<?php
								++$tab_index;
							endwhile;
							?>
						</div>

						<div>
						<?php
							$content_index = 0;
						while ( have_rows( 'tabs' ) ) :
							the_row();
							$tab_content = get_sub_field( 'content' );
							?>
								<div x-show="activeTab === <?php echo $content_index; ?>" x-transition class="tab-content">
								<?php echo wp_kses_post( $tab_content ); ?>
								</div>
							<?php
							++$content_index;
							endwhile;
						?>
						</div>
					</div>

				</div>
			</div>

		</div>
	<?php endif; ?>
<?php endif; ?>
