<?php
/**
 * tabs Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes
 */


$block_name = 'tabs';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Card default classes
$tab_default_classes = '';

if( get_field('style') === 'light' ){
	$card_styles = 'py-8 border-2 border-primary bg-white h-full rounded-xl';
} elseif( get_field('style') === 'dark' ){
	$card_styles = 'content-card-dark overflow-hidden pb-6 border-2 border-primary rounded-4xl';
} else{
	$card_styles = 'content-card-accent max-w-[340px] mx-auto relative py-4 bg-white lg:h-full';
}

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
	$tab_default_classes
);

$classes = implode( ' ', $all_classes );

?>

<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $classes ?>">

<div x-data="{ activeTab: 'details' }" class="space-y-2">
  <ul class="flex gap-2">
    <li>
      <a
        x-on:click.prevent="activeTab = 'details'"
        :class="{ 'text-indigo-600': activeTab === 'details' }"
        class="underline"
        href="#details"
      >
        Details
      </a>
    </li>

    <li>
      <a
        x-on:click.prevent="activeTab = 'specs'"
        :class="{ 'text-indigo-600': activeTab === 'specs' }"
        class="underline"
        href="#specs"
      >
        Specs
      </a>
    </li>

    <li>
      <a
        x-on:click.prevent="activeTab = 'reviews'"
        :class="{ 'text-indigo-600': activeTab === 'reviews' }"
        class="underline"
        href="#reviews"
      >
        Reviews
      </a>
    </li>
  </ul>

  <div>
    <div x-cloak x-show="activeTab === 'details'">Details</div>
    <div x-cloak x-show="activeTab === 'specs'">Specs</div>
    <div x-cloak x-show="activeTab === 'reviews'">Reviews</div>
  </div>
</div>




</div>

