<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes
 * py-3 sm:inline-block !lg:flex !hidden lg:flex! hidden! lg:hidden!
 */


$block_name = 'ribbon';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Card default classes
$cta_default_classes = 'relative py-4 border-y-2 border-primary';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
	$cta_default_classes,
);

$classes = implode( ' ', $all_classes );

?>

<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $classes; ?>">
	<div class="flex flex-row">
		<div class="w-full xl:basis-1/4">
			<div style="clip-path: polygon(0 0, 100% 0%, 95% 100%, 0% 100%);">
				<img src="<?php echo esc_url( get_field( 'img_1' )['url'] ); ?>" class="w-full"/>
			</div>
		</div>
		<div class="hidden xl:flex w-full xl:basis-1/4">
			<div style="clip-path: polygon(5% 0, 100% 0%, 95% 100%, 0% 100%);">
			<img src="<?php echo esc_url( get_field( 'img_2' )['url'] ); ?>" class="w-full"/>
			</div>
		</div>
		<div class="flex w-full has-dark-gradient-gradient-background xl:basis-1/4" style="clip-path: polygon(5% 0, 100% 0%, 95% 100%, 0% 100%);">
			<div class="flex mx-auto" style="clip-path: polygon(0 0, 100% 0%, 95% 100%, 0% 100%);">
				<InnerBlocks class="self-center space-y-6 p-6 px-8 text-center"/>
			</div>
		</div>
		<div class="hidden xl:flex w-full xl:basis-1/4">
			<div style="clip-path: polygon(5% 0, 100% 0%, 100% 100%, 0% 100%);">
			<img src="<?php echo esc_url( get_field( 'img_3' )['url'] ); ?>" class="w-full"/>
			</div>
		</div>
	</div>
</div>

