<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * my-2 my-4 my-6 my-8 my-10 my-12 my-14 my-16 my-18 my-20 my-22 my-24
 * md:my-2 md:my-4 md:my-6 md:my-8 md:my-10 md:my-12 md:my-14 md:my-16 md:my-18 md:my-20 md:my-22 md:my-24
 * lg:my-2 lg:my-4 lg:my-6 lg:my-8 lg:my-10 lg:my-12 lg:my-14 lg:my-16 lg:my-18 lg:my-20 lg:my-22 lg:my-24
 * xl:my-2 xl:my-4 xl:my-6 xl:my-8 xl:my-10 xl:my-12 lx:my-14 xl:my-16 xl:my-18 xl:my-20 xl:my-22 xl:my-24
 * 2xl:my-2 2xl:my-4 2xl:my-6 2xl:my-8 2xl:my-10 2xl:my-12 2lx:my-14 2xl:my-16 2xl:my-18 2xl:my-20 2xl:my-22 2xl:my-24
 * !mb-0
 */


$block_name = 'team';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes
);

$classes = implode( ' ', $all_classes );

?>

<?php if($is_preview): ?>
	<p>team</p>
	<?php if( have_rows('team') ): ?>
		<div class="flex flex-wrap justify-center -m-6">
			<?php while( have_rows('team') ): the_row(); ?>
				<div class="box-border p-6 w-1/2 lg:w-1/4 text-center">
					<?php if (get_sub_field('img')): ?>
						<img src="<?php echo get_sub_field('img')['url'] ?>" class="block mx-auto !my-0 border-2 border-primary rounded-full w-20 not-prose" alt="" />
					<?php endif; ?>
					<?php if (get_sub_field('title')): ?>
						<h4 class="my-0 not-prose"><?php echo get_sub_field('title') ?></h4>
					<?php endif; ?>
					<?php if (get_sub_field('position')): ?>
						<h5 class="my-0 not-prose"><?php echo get_sub_field('position') ?></h5>
					<?php endif; ?>
					<?php if (get_sub_field('bio')): ?>
						<button>Read Bio</button>
					<?php endif; ?>
				</div>
			<?php endwhile ?>
		</div>
	<?php endif; ?>

<?php else: ?>

	<?php if( have_rows('team') ): ?>
		<div class="flex flex-wrap justify-center -m-6">
			<?php while( have_rows('team') ): the_row(); ?>
				<div class="box-border p-6 w-1/2 lg:w-1/4 text-center">
					<?php
					$name = get_sub_field('title');
					$position = get_sub_field('position');
					$photo = get_sub_field('img');
					$bio = get_sub_field('bio');
					?>
					<div x-data="{ open: false }" x-effect="document.body.classList.toggle('overflow-hidden', open);document.querySelectorAll('.navbar-reveal').forEach(el => el.classList.toggle('hidden', open));" class="text-center">
						<div class="space-y-4 text-white">
							<?php if ( $photo ) : ?>
								<img src="<?php echo esc_url($photo['url']); ?>" alt="<?php echo esc_attr($photo['alt']); ?>" class="block mx-auto border-2 border-primary rounded-full w-full max-w-75 not-prose">
							<?php endif; ?>
							<div>
								<h3 class="font-display h4"><?php echo esc_html($name); ?></h3>
								<h4 class="font-semibold text-lg"><?php echo esc_html($position); ?></h4>
							</div>
							<div class="wp-block-buttons wp-block-buttons-is-layout-flex is-layout-flex justify-center">
								<div class="wp-block-button has-icon__next">
									<button @click="open = true" class="wp-block-button__link rounded-[30px] has-default-gradient-gradient-background has-background wp-element-button" href="https://akvm.test/about/" style="font-style:normal;font-weight:600;text-transform:uppercase">
										Read Bio
										<span class="wp-block-button__link-icon" aria-hidden="true"><svg viewBox='0 0 13 12' xmlns='http://www.w3.org/2000/svg'>
											<path d='M1.2,0 L2.22044605e-14,1 L4.5,6 L2.22044605e-14,11 L1.1,12 L6.6,6 L1.2,0 Z M7.2,0 L6.1,1 L10.6,6 L6.1,11 L7.2,12 L12.7,6 L7.2,0 L7.2,0 Z'></path></svg>
										</span>
									</button>
								</div>
							</div>
						</div>

						<!-- Modal (unique to this repeater row) -->
						<div
							x-show="open"
							x-transition.opacity
							@keydown.escape.window="open = false"
							@click.self="open = false"
							class="z-50 fixed inset-0 flex justify-center items-center bg-black/70 backdrop-blur-sm overflow-hidden"
							x-cloak
						>
							<div
								x-show="open"
								x-transition
								class="relative bg-white shadow-xl mx-4 pt-6 rounded-xl w-full max-w-[400px] lg:max-w-[1200px] max-h-[90vh] overflow-y-auto"
							>
								<button
									@click="open = false"
									class="top-3 right-3 absolute text-gray-500 hover:text-gray-700"
								>
									✕
								</button>

								<div class="lg:gap-6 xl:gap-12 grid grid-cols-12">
									<div class="relative col-span-12 lg:col-span-4 lg:min-h-[333px]">
										<?php if ( $photo ) : ?>
											<img src="<?php echo esc_url($photo['url']); ?>" alt="<?php echo esc_attr($photo['alt']); ?>" class="lg:absolute lg:inset-0 my-4 lg:my-0 w-full lg:h-full lg:object-center lg:object-cover">
										<?php endif; ?>
									</div>
									<div class="col-span-12 lg:col-span-8 p-4 lg:p-0 lg:pr-6 lg:pb-6 text-left">
										<h4 class="mb-1 font-display font-semibold h4"><?php echo esc_html($name); ?></h4>
										<h5 class="mb-4 font-semibold text-lg"><?php echo esc_html($position); ?></h5>
										<div class="[&>p]:text-[15px]">
											<?php echo $bio; ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php endwhile ?>
		</div>
	<?php endif; ?>

<?php endif; ?>
