<?php
/**
 * Blog Grid Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 * icon-[line-md--speed-twotone-loop] icon-[line-md--speedometer-loop] size-40
 */

$block_name = 'blog-grid';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id!
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];


// Additional editor classes including $block['style'] defined in block.json.
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode.
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

$the_query = new WP_Query(
	array(
		'post_type'      => 'post',
		'posts_per_page' => 100,
		'order'          => 'ASC',
	)
);
?>

<div class="flex flex-wrap justify-center -m-6">
	<?php while ( $the_query->have_posts() ) : ?>
		<?php
		$the_query->the_post();
		$blog_post_id    = get_the_ID();
		$blog_post_url   = get_the_permalink();
		$thumbnail_id    = get_post_thumbnail_id( $blog_post_id );
		$thumbnail_alt   = get_post_meta( $thumbnail_id, '_wp_attachment_image_alt', true );
		$thumbnail_url   = get_the_post_thumbnail_url( $blog_post_id, 'medium_large' );
		$truncated_title = substr(
			get_the_title(),
			0,
			45
		);
		?>
		<div class="box-border p-6 w-full md:w-1/2 xl:w-1/3 text-center">
			<a href="<?php echo esc_url( $blog_post_url ); ?>" class="block bg-foreground bg-linear-to-t from-bg-foreground to-stone-900 hover:shadow-xl border-2 border-primary rounded-2xl w-full overflow-hidden transition-shadow">
				<?php
				if ( get_the_post_thumbnail( $blog_post_id ) ) :
					?>
					<div class="relative aspect-9/5">
						<img class="absolute w-full h-full object-cover" src = "<?php echo esc_url( $thumbnail_url ); ?>" alt="<?php echo esc_attr( $thumbnail_alt ); ?>" / >
					</div>
				<?php endif; ?>
				<div class="py-4 text-white">
					<h3 class="font-display text-2xl"><?php echo esc_html( truncate_at_word( get_the_title() ) ); ?></h3>
					<span><?php echo get_the_date(); ?></span>
				</div>
			</a>
		</div>
	<?php endwhile; ?>
</div>
